-- Откуда у сети снимки — в базе, а не в цепочке if внутри скрипта.
-- Платформа важнее сети: подключить сеть на Olo значит записать строку.
-- Список видов — из `adapters/photo_sources.KINDS`, см. sql_check().
alter table chains
  add column website text,
  add column photo_source_kind text
    check (photo_source_kind in ('olo', 'sanity-rbi', 'contentful-gotofoods', 'collected', 'mcdonalds-snapshot', 'panera-aem', 'starbucks-scene7', 'jerseymikes-api', 'quiznos-site', 'subway-newsroom', 'chickfila-wordpress', 'tacobell-nextjs', 'culvers-nextjs', 'einstein-wordpress')),
  add column photo_source_url text,
  add column photo_rights text;

comment on column chains.website is 'Национальный сайт США — не страница франшизы.';
comment on column chains.photo_source_kind is 'Платформа снимков: чем читать. Пусто — снимков брать негде (пока).';
comment on column chains.photo_source_url is 'Страница меню для платформенного адаптера и для подписи «источник».';
comment on column chains.photo_rights is 'Строка прав рядом с каждым снимком: сеть разрешила использовать с упоминанием.';

update chains set website = '7-eleven.com' where slug = '7-eleven';
update chains set website = 'applebees.com' where slug = 'applebee-s';
update chains set website = 'arbys.com' where slug = 'arby-s';
update chains set website = 'auntieannes.com' where slug = 'auntie-anne-s';
update chains set website = 'baskinrobbins.com' where slug = 'baskin-robbins';
update chains set website = 'bjsrestaurants.com' where slug = 'bj-s-restaurant-brewhouse';
update chains set website = 'bobevans.com' where slug = 'bob-evans';
update chains set website = 'bojangles.com' where slug = 'bojangles';
update chains set website = 'bonefishgrill.com' where slug = 'bonefish-grill';
update chains set website = 'bostonmarket.com' where slug = 'boston-market';
update chains set website = 'bk.com' where slug = 'burger-king';
update chains set website = 'cpk.com' where slug = 'california-pizza-kitchen';
update chains set website = 'captainds.com' where slug = 'captain-d-s';
update chains set website = 'carlsjr.com' where slug = 'carl-s-jr';
update chains set website = 'carrabbas.com' where slug = 'carrabba-s-italian-grill';
update chains set website = 'caseys.com' where slug = 'casey-s-general-store';
update chains set website = 'checkers.com' where slug = 'checker-s-drive-in-rallys';
update chains set website = 'chick-fil-a.com' where slug = 'chick-fil-a';
update chains set website = 'chilis.com' where slug = 'chili-s';
update chains set website = 'chipotle.com' where slug = 'chipotle';
update chains set website = 'chuckecheese.com' where slug = 'chuck-e-cheese';
update chains set website = 'churchs.com' where slug = 'church-s-chicken';
update chains set website = 'cicis.com' where slug = 'ci-ci-s-pizza';
update chains set website = 'culvers.com' where slug = 'culver-s';
update chains set website = 'dairyqueen.com' where slug = 'dairy-queen';
update chains set website = 'deltaco.com' where slug = 'del-taco';
update chains set website = 'dennys.com' where slug = 'denny-s';
update chains set website = 'dickeys.com' where slug = 'dickey-s-barbeque-pit';
update chains set website = 'dominos.com' where slug = 'dominos';
update chains set website = 'dunkindonuts.com' where slug = 'dunkin-donuts';
update chains set website = 'einsteinbros.com' where slug = 'einstein-bros';
update chains set website = 'elpolloloco.com' where slug = 'el-pollo-loco';
update chains set website = 'famousdaves.com' where slug = 'famous-dave-s';
update chains set website = 'firehousesubs.com' where slug = 'firehouse-subs';
update chains set website = 'fiveguys.com' where slug = 'five-guys';
update chains set website = 'friendlys.com' where slug = 'friendly-s';
update chains set website = 'frischs.com' where slug = 'frisch-s-big-boy';
update chains set website = 'goldencorral.com' where slug = 'golden-corral';
update chains set website = 'hardees.com' where slug = 'hardee-s';
update chains set website = 'hooters.com' where slug = 'hooters';
update chains set website = 'ihop.com' where slug = 'ihop';
update chains set website = 'in-n-out.com' where slug = 'in-n-out-burger';
update chains set website = 'jackinthebox.com' where slug = 'jack-in-the-box';
update chains set website = 'jamba.com' where slug = 'jamba-juice';
update chains set website = 'jasonsdeli.com' where slug = 'jason-s-deli';
update chains set website = 'jerseymikes.com' where slug = 'jersey-mike-s-subs';
update chains set website = 'jimmyjohns.com' where slug = 'jimmy-john-s';
update chains set website = 'joescrabshack.com' where slug = 'joe-s-crab-shack';
update chains set website = 'kfc.com' where slug = 'kfc';
update chains set website = 'krispykreme.com' where slug = 'krispy-kreme';
update chains set website = 'krystal.com' where slug = 'krystal';
update chains set website = 'littlecaesars.com' where slug = 'little-caesars';
update chains set website = 'ljsilvers.com' where slug = 'long-john-silver-s';
update chains set website = 'longhornsteakhouse.com' where slug = 'longhorn-steakhouse';
update chains set website = 'marcos.com' where slug = 'marco-s-pizza';
update chains set website = 'mcalistersdeli.com' where slug = 'mcalister-s-deli';
update chains set website = 'mcdonalds.com' where slug = 'mcdonald-s';
update chains set website = 'moes.com' where slug = 'moe-s-southwest-grill';
update chains set website = 'noodles.com' where slug = 'noodles-company';
update chains set website = 'ocharleys.com' where slug = 'o-charley-s';
update chains set website = 'olivegarden.com' where slug = 'olive-garden';
update chains set website = 'ontheborder.com' where slug = 'on-the-border';
update chains set website = 'outback.com' where slug = 'outback-steakhouse';
update chains set website = 'pandaexpress.com' where slug = 'panda-express';
update chains set website = 'panerabread.com' where slug = 'panera-bread';
update chains set website = 'papajohns.com' where slug = 'papa-john-s';
update chains set website = 'papamurphys.com' where slug = 'papa-murphy-s';
update chains set website = 'perkinsrestaurants.com' where slug = 'perkins';
update chains set website = 'pfchangs.com' where slug = 'pf-chang-s';
update chains set website = 'pizzahut.com' where slug = 'pizza-hut';
update chains set website = 'popeyes.com' where slug = 'popeyes';
update chains set website = 'potbelly.com' where slug = 'potbelly-sandwich-shop';
update chains set website = 'qdoba.com' where slug = 'qdoba';
update chains set website = 'quiznos.com' where slug = 'quiznos';
update chains set website = 'redlobster.com' where slug = 'red-lobster';
update chains set website = 'redrobin.com' where slug = 'red-robin';
update chains set website = 'macaronigrill.com' where slug = 'romano-s-macaroni-grill';
update chains set website = 'roundtablepizza.com' where slug = 'round-table-pizza';
update chains set website = 'rubytuesday.com' where slug = 'ruby-tuesday';
update chains set website = 'sbarro.com' where slug = 'sbarro';
update chains set website = 'sheetz.com' where slug = 'sheetz';
update chains set website = 'sonicdrivein.com' where slug = 'sonic';
update chains set website = 'starbucks.com' where slug = 'starbucks';
update chains set website = 'steaknshake.com' where slug = 'steak-n-shake';
update chains set website = 'subway.com' where slug = 'subway';
update chains set website = 'tacobell.com' where slug = 'taco-bell';
update chains set website = 'tgifridays.com' where slug = 'tgi-friday-s';
update chains set website = 'thecapitalgrille.com' where slug = 'the-capital-grille';
update chains set website = 'timhortons.com' where slug = 'tim-hortons';
update chains set website = 'wawa.com' where slug = 'wawa';
update chains set website = 'wendys.com' where slug = 'wendy-s';
update chains set website = 'whataburger.com' where slug = 'whataburger';
update chains set website = 'whitecastle.com' where slug = 'white-castle';
update chains set website = 'wingstop.com' where slug = 'wingstop';
update chains set website = 'yardhouse.com' where slug = 'yard-house';
update chains set website = 'zaxbys.com' where slug = 'zaxby-s';

update chains set photo_source_kind = 'olo', photo_source_url = 'https://www.applebees.com/en/menu', photo_rights = '© Applebee''s. Used with permission. Source: applebees.com' where slug = 'applebee-s';
update chains set photo_source_kind = 'contentful-gotofoods', photo_source_url = 'https://www.auntieannes.com/menu', photo_rights = '© Auntie Anne''s. Used with permission. Source: auntieannes.com' where slug = 'auntie-anne-s';
update chains set photo_source_kind = 'sanity-rbi', photo_source_url = 'https://www.bk.com/menu', photo_rights = '© Burger King Company LLC. Used with permission. Source: bk.com' where slug = 'burger-king';
update chains set photo_source_kind = 'chickfila-wordpress', photo_source_url = 'https://www.chick-fil-a.com/menu', photo_rights = '© CFA Properties, Inc. Used with permission. Source: chick-fil-a.com' where slug = 'chick-fil-a';
update chains set photo_source_kind = 'olo', photo_source_url = 'https://www.chilis.com/menu', photo_rights = '© Chili''s. Used with permission. Source: chilis.com' where slug = 'chili-s';
update chains set photo_source_kind = 'culvers-nextjs', photo_source_url = 'https://www.culvers.com/menu', photo_rights = '© Culver Franchising System, LLC. Used with permission. Source: culvers.com' where slug = 'culver-s';
update chains set photo_source_kind = 'einstein-wordpress', photo_source_url = 'https://www.einsteinbros.com/menu', photo_rights = '© Einstein Noah Restaurant Group, Inc. Used with permission. Source: einsteinbros.com' where slug = 'einstein-bros';
update chains set photo_source_kind = 'sanity-rbi', photo_source_url = 'https://www.firehousesubs.com/menu', photo_rights = '© Firehouse Restaurant Group, Inc. Used with permission. Source: firehousesubs.com' where slug = 'firehouse-subs';
update chains set photo_source_kind = 'contentful-gotofoods', photo_source_url = 'https://www.jamba.com/menu', photo_rights = '© Jamba Juice. Used with permission. Source: jamba.com' where slug = 'jamba-juice';
update chains set photo_source_kind = 'jerseymikes-api', photo_source_url = 'https://www.jerseymikes.com/menu', photo_rights = '© Jersey Mike''s Franchise Systems, Inc. Used with permission. Source: jerseymikes.com' where slug = 'jersey-mike-s-subs';
update chains set photo_source_kind = 'contentful-gotofoods', photo_source_url = 'https://www.mcalistersdeli.com/menu', photo_rights = '© McAlister''s Deli. Used with permission. Source: mcalistersdeli.com' where slug = 'mcalister-s-deli';
update chains set photo_source_kind = 'mcdonalds-snapshot', photo_source_url = 'https://www.mcdonalds.com/us/en-us/about-our-food/nutrition-calculator.html', photo_rights = '© McDonald''s Corporation. Used with permission. Source: mcdonalds.com' where slug = 'mcdonald-s';
update chains set photo_source_kind = 'contentful-gotofoods', photo_source_url = 'https://www.moes.com/menu', photo_rights = '© Moe''s Southwest Grill. Used with permission. Source: moes.com' where slug = 'moe-s-southwest-grill';
update chains set photo_source_kind = 'panera-aem', photo_source_url = 'https://www.panerabread.com/en-us/menu.html', photo_rights = '© Panera Bread. Used with permission. Source: panerabread.com' where slug = 'panera-bread';
update chains set photo_source_kind = 'sanity-rbi', photo_source_url = 'https://www.popeyes.com/menu', photo_rights = '© Popeyes Louisiana Kitchen, Inc. Used with permission. Source: popeyes.com' where slug = 'popeyes';
update chains set photo_source_kind = 'quiznos-site', photo_source_url = 'https://www.quiznos.com/menu', photo_rights = '© Quiznos. Used with permission. Source: quiznos.com' where slug = 'quiznos';
update chains set photo_source_kind = 'starbucks-scene7', photo_source_url = 'https://www.starbucks.com/menu', photo_rights = '© Starbucks Corporation. Used with permission. Source: starbucks.com' where slug = 'starbucks';
update chains set photo_source_kind = 'subway-newsroom', photo_source_url = 'https://newsroom.subway.com/Menu-Items', photo_rights = '© Subway IP LLC. Used with permission. Source: newsroom.subway.com' where slug = 'subway';
update chains set photo_source_kind = 'tacobell-nextjs', photo_source_url = 'https://www.tacobell.com/food', photo_rights = '© Taco Bell Corp. Used with permission. Source: tacobell.com' where slug = 'taco-bell';
update chains set photo_source_kind = 'sanity-rbi', photo_source_url = 'https://www.timhortons.com/menu', photo_rights = '© Tim Hortons. Used with permission. Source: timhortons.com' where slug = 'tim-hortons';
update chains set photo_source_kind = 'collected', photo_source_url = 'https://www.whitecastle.com/menu', photo_rights = '© White Castle System, Inc. Used with permission. Source: whitecastle.com' where slug = 'white-castle';
